force-app/main/default/objects/BatchFramework__c/BatchFramework__c.object-meta.xml
<CustomObject>
    <label>Batch Framework</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>Batch Framework</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Framework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchFramework__c/fields/BatchClassName__c.field-meta.xml
<CustomField>
    <fullName>BatchClassName__c</fullName>
    <label>Batch Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BatchFramework__c/fields/NextExecutionTime__c.field-meta.xml
<CustomField>
    <fullName>NextExecutionTime__c</fullName>
    <label>Next Execution Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchFrameworkSelector.cls
public with sharing class BatchFrameworkSelector {
    public static BatchFrameworkSelector instance;
    public BatchFrameworkSelector() {}

    public static BatchFrameworkSelector getInstance(){
        if (intance == null) {
            instance = new BatchFrameworkSelector();
        }
        return instance;
    }

    public List<BatchFramework__c> getValidBatchClassDetails(){
        DateTime currentDateTime = BatchFrameworkUtility.getInstance().getCurrentDateTime();
        return [
            SELECT 
                Id,
                BatchClassName__c
            FROM BatchFramework__c
            WHERE IsActive__c = true
            AND NextExecutionTime__c != null
            AND NextExecutionTime__c <= :currentDateTime
        ];
    }

    public BatchFramework__c getBatchFrameworkRecordById(Id recordId) {
        return [
            SELECT 
                Id,
                BatchClassName__c,
                NextExecutionTime__c
            FROM BatchFramework__c
            WHERE Id = :recordId
            LIMIT 1
        ];
    }
}